(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



SetDirectory["~/ed/k/mma/gdo"];
Once[<<"StandardVersion.m"];

VerificationTest[
	Subscript[d\[CapitalDelta], 1->2,3]//Subscript[d\[CapitalDelta], 2->1,2],
	Subscript[d\[CapitalDelta], 1->1,2]//Subscript[d\[CapitalDelta], 2->2,3],
TestID->"Coassociativity"]
VerificationTest[
	Subscript[d\[CapitalDelta], i->1,2] Subscript[d\[CapitalDelta], j->3,4]//Subscript[dm, 1,3->i]//Subscript[dm, 2,4->j],
	Subscript[dm, i,j->k]//Subscript[d\[CapitalDelta], k->i,j],
TestID->"Algebra morphism"]
VerificationTest[
	Subscript[dm, 2,3->k]//Subscript[dm, 1,k->k],
	Subscript[dm, 1,2->k]//Subscript[dm, k,3->k],
TestID->"Associativity"]

VerificationTest[
	Normal@(Subscript[d\[CapitalDelta], i->1,2]//Subscript[dS, 1]//Subscript[dm, 1,2->1]),
	\!\(\*SubscriptBox[\(\[DoubleStruckCapitalE]\), \({i} \[Rule] {1}\)]\)[0,0,1],
TestID->"Antipode L"]
VerificationTest[
	Normal@(Subscript[d\[CapitalDelta], i->1,2]//Subscript[dS, 2]//Subscript[dm, 1,2->1]),
	\!\(\*SubscriptBox[\(\[DoubleStruckCapitalE]\), \({i} \[Rule] {1}\)]\)[0,0,1],
TestID->"Antipode R"]

VerificationTest[
	Subscript[R, 1,3]//Subscript[d\[CapitalDelta], 1->1,2],
	Subscript[R, 1,3] Subscript[R, 2,4]//Subscript[dm, 3,4->3],
TestID->"Quasitriangular 1"]
VerificationTest[
	Subscript[R, 1,3]//Subscript[d\[CapitalDelta], 3->2,3],
	Subscript[R, 1,3] Subscript[R, 0,2]//Subscript[dm, 1,0->1],
TestID->"Quasitriangular 2"]
VerificationTest[
	Subscript[d\[CapitalDelta], i->k,j] Subscript[R, 1,2]//Subscript[dm, j,1->1]//Subscript[dm, k,2->2],
	Subscript[R, 1,2] Subscript[d\[CapitalDelta], i->j,k]//Subscript[dm, 1,j->1]//Subscript[dm, 2,k->2],
TestID->"Quasitriangular 3"]

VerificationTest[
	Subscript[R, 1,2]//Subscript[aS, 2],
	Subscript[\!\(\*OverscriptBox[\(R\), \(_\)]\), 1,2],
TestID->"R-matrix inverse"]
